/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-west-2",
  aws_cognito_identity_pool_id:
    "us-west-2:d600e8b6-a8e3-4a84-810f-1ef352e732ac",
  aws_cognito_region: "us-west-2",
  aws_user_pools_id: "us-west-2_4iGOZCN27",
  aws_user_pools_web_client_id: "1p3sh7m1f9r40vvn7d4fobj7qq",
  oauth: {
    domain: "auth.sydneystirling.com.auth.us-west-2.amazoncognito.com",
    scope: ["aws.cognito.signin.user.admin", "email", "openid", "profile"],
    redirectSignIn: "https://quiz.sydneystirling.com/",
    redirectSignOut: "https://sydneystirling.com/",
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
}

export default awsmobile
